name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Set image name and tag
      run: |
        echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/lynxworkspace" >> $GITHUB_ENV
        echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .

    - name: Push the Docker image
      run: |
        docker push $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:latest
